# Generated by Django 3.2.22 on 2024-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveIntegerField(choices=[(1, 'Ростов-на-Дону'), (2, 'Краснодар'), (3, 'Сочи')], null=True, verbose_name='Город')),
                ('num', models.IntegerField(null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='KRDSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150, null=True, verbose_name='Данные клиента')),
                ('date', models.DateField(default=None, verbose_name='Дата записи ')),
                ('time_visit', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=5, null=True, unique=True, verbose_name='Время')),
                ('typePriem', models.PositiveIntegerField(choices=[(1, 'Первичный'), (2, 'Вторичный'), (3, 'Обучение')], null=True, verbose_name='Тип приема')),
            ],
            options={
                'verbose_name': 'Расписание, Краснодар',
                'verbose_name_plural': 'Расписание, Краснодар',
            },
        ),
        migrations.CreateModel(
            name='RNDSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150, null=True, verbose_name='Данные клиента')),
                ('date', models.DateField(default=None, verbose_name='Дата записи ')),
                ('time_visit', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=5, null=True, unique=True, verbose_name='Время')),
                ('typePriem', models.PositiveIntegerField(choices=[(1, 'Первичный'), (2, 'Вторичный'), (3, 'Обучение')], null=True, verbose_name='Тип приема')),
            ],
            options={
                'verbose_name': 'Расписание, Ростов-на-Дону',
                'verbose_name_plural': 'Расписание, Ростов-на-Дону',
            },
        ),
        migrations.CreateModel(
            name='SCHSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150, null=True, verbose_name='Данные клиента')),
                ('date', models.DateField(default=None, verbose_name='Дата записи ')),
                ('time_visit', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=5, null=True, unique=True, verbose_name='Время')),
                ('typePriem', models.PositiveIntegerField(choices=[(1, 'Первичный'), (2, 'Вторичный'), (3, 'Обучение')], null=True, verbose_name='Тип приема')),
            ],
            options={
                'verbose_name': 'Расписание, Сочи',
                'verbose_name_plural': 'Расписание, Сочи',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('midname', models.CharField(blank=True, max_length=55, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('date', models.DateField(default=None, verbose_name='Дата записи')),
                ('time_visit', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=5, null=True, unique=True, verbose_name='Время')),
                ('typepr', models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный'), ('Обучение', 'Обучение')], default=None, max_length=9, null=True, verbose_name='Тип приема')),
                ('city', models.CharField(choices=[('Ростов-на-Дону', 'Ростов-на-Дону'), ('Краснодар', 'Краснодар'), ('Сочи', 'Сочи')], default=None, max_length=30, null=True, verbose_name='Город')),
                ('visit', models.PositiveIntegerField(choices=[(0, 'Запись отсутствует'), (1, 'Посетил'), (2, 'Не посетил')], default=0, null=True, verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('date', 'time_visit', 'city')},
            },
        ),
    ]
