# Generated by Django 3.2.22 on 2023-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('date_application', models.DateField(default=None, verbose_name='Дата обращения')),
                ('type_priem', models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный')], default=None, max_length=9, null=True, verbose_name='Тип приема')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='PatientsCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=300, null=True, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=30, null=True, verbose_name='Имя')),
                ('midname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('address_obl', models.CharField(max_length=70, null=True, verbose_name='Область')),
                ('address_city', models.CharField(max_length=70, null=True, verbose_name='Населенный пункт')),
                ('address_street', models.CharField(max_length=70, null=True, verbose_name='Улица')),
                ('address_house', models.CharField(max_length=10, null=True, verbose_name='Номер дома')),
                ('address_korpus', models.CharField(blank=True, max_length=70, null=True, verbose_name='Корпус')),
                ('address_flat', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('work_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('work_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('is_dependent', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=3, verbose_name='Иждевенец')),
            ],
        ),
    ]
