# Generated by Django 3.2.22 on 2023-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Дата обращения'),
        ),
    ]
