# Generated by Django 3.2.22 on 2023-11-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientscards',
            options={'verbose_name': 'Карточка пациента', 'verbose_name_plural': 'Карточки пациентов'},
        ),
    ]
