# Generated by Django 3.2.22 on 2023-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='time',
            field=models.TimeField(default=None, null=True, verbose_name='Время записи'),
        ),
    ]
