# Generated by Django 3.2.22 on 2023-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_alter_patientscards_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='type_priem',
            field=models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный'), ('Обучение', 'Обучение')], default=None, max_length=9, null=True, verbose_name='Тип приема'),
        ),
    ]
