# Generated by Django 3.2.22 on 2023-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_alter_applications_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AddField(
            model_name='applications',
            name='time',
            field=models.TimeField(default=None, null=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date',
            field=models.DateField(default=None, verbose_name='Дата записи'),
        ),
    ]
