# Generated by Django 3.2.22 on 2023-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_alter_applications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='midname',
            field=models.CharField(max_length=55, null=True, verbose_name='Отчество'),
        ),
    ]
