# Generated by Django 3.2.22 on 2024-03-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_alter_applications_time_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='time_visit',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('date', 'time', 'city')},
        ),
    ]
