# Generated by Django 3.2.22 on 2023-11-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0003_alter_applications_type_priem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
