# Generated by Django 3.2.22 on 2023-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0003_applications_midname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='midname',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Отчество'),
        ),
    ]
