# Generated by Django 3.2.22 on 2023-11-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0004_alter_applications_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='date_application',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='middle_name',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='type_priem',
            new_name='typepr',
        ),
    ]
