# Generated by Django 3.2.22 on 2023-11-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0005_cabinets'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='cab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personals.cabinets', verbose_name='Кабинет'),
        ),
    ]
