# Generated by Django 3.2.22 on 2023-11-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0006_applications_cab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='cab',
        ),
        migrations.DeleteModel(
            name='Cabinets',
        ),
    ]
