# Generated by Django 3.2.22 on 2023-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0009_alter_applications_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='visit',
            field=models.PositiveIntegerField(choices=[(0, 'Посетил'), (1, 'Не посетил')], default=0, null=True, verbose_name='Посещение'),
        ),
    ]
