# Generated by Django 3.2.22 on 2023-11-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0010_applications_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='visit',
            field=models.PositiveIntegerField(choices=[(0, 'Не посетил'), (1, 'Посетил')], default=0, null=True, verbose_name='Посещение'),
        ),
    ]
