# Generated by Django 3.2.22 on 2023-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0012_alter_applications_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='visit',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Не посетил'), (1, 'Посетил')], null=True, verbose_name='Посещение'),
        ),
    ]
