# Generated by Django 3.2.22 on 2023-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0013_alter_applications_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='visit',
            field=models.PositiveIntegerField(choices=[(0, 'Запись отсутствует'), (1, 'Посетил'), (2, 'Не посетил')], default=0, null=True, verbose_name='Посещение'),
        ),
    ]
