# Generated by Django 3.2.22 on 2023-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='Номер телефона')),
                ('date_application', models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный')], default=None, max_length=15, verbose_name='Дата обращения')),
                ('type_priem', models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный')], default=None, max_length=9, null=True, verbose_name='Тип приема')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
