# Generated by Django 3.2.22 on 2023-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_application',
            field=models.DateField(default=None, verbose_name='Дата обращения'),
        ),
    ]
