# Generated by Django 3.2.22 on 2023-10-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0002_alter_applications_date_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_num', models.CharField(max_length=3, null=True, verbose_name='Номер кабинета')),
                ('cabinet_floor', models.IntegerField(choices=[(0, 'Цокольный'), (1, 'Первый'), (2, 'Второй')], null=True, verbose_name='Этаж кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
