# Generated by Django 3.2.22 on 2023-10-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0003_cabinets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='cabinet_num',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Номер кабинета'),
        ),
    ]
