# Generated by Django 3.2.22 on 2023-10-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0004_alter_cabinets_cabinet_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinets',
            name='cabinet_num',
            field=models.IntegerField(null=True, verbose_name='Номер кабинета'),
        ),
    ]
