# Generated by Django 3.2.22 on 2023-11-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0005_alter_cabinets_cabinet_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRDCabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_num', models.IntegerField(null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='RNDCabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_num', models.IntegerField(null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='SCHCabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_num', models.IntegerField(null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.DeleteModel(
            name='Cabinets',
        ),
    ]
