# Generated by Django 3.2.22 on 2023-11-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0006_auto_20231102_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krdcabinets',
            options={'verbose_name': 'Кабинет, Краснодар', 'verbose_name_plural': 'Кабинеты, Краснодар'},
        ),
        migrations.AlterModelOptions(
            name='rndcabinets',
            options={'verbose_name': 'Кабинет, Ростов-на-Дону', 'verbose_name_plural': 'Кабинеты, Ростов-на-Дону'},
        ),
        migrations.AlterModelOptions(
            name='schcabinets',
            options={'verbose_name': 'Кабинет, Сочи', 'verbose_name_plural': 'Кабинеты, Сочи'},
        ),
    ]
