# Generated by Django 3.2.22 on 2023-11-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0007_auto_20231102_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
