# Generated by Django 3.2.22 on 2023-11-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0008_delete_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRDSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150, null=True, verbose_name='Данные клиента')),
                ('date', models.DateField(default=None, verbose_name='Дата записи ')),
                ('typePriem', models.PositiveIntegerField(choices=[(1, 'Первичный'), (2, 'Вторичный'), (3, 'Обучение')], null=True, verbose_name='Тип приема')),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skyreg.krdcabinets', verbose_name='Кабинет')),
            ],
        ),
    ]
