# Generated by Django 3.2.22 on 2023-11-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0009_krdschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krdschedule',
            options={'verbose_name': 'Расписание, Краснодар', 'verbose_name_plural': 'Расписание, Краснодар'},
        ),
    ]
