# Generated by Django 3.2.22 on 2023-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0011_rndschedule_schschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rndschedule',
            options={'verbose_name': 'Расписание, Ростов-на-Дону', 'verbose_name_plural': 'Расписание, Ростов-на-Дону'},
        ),
        migrations.AlterModelOptions(
            name='schschedule',
            options={'verbose_name': 'Расписание, Сочи', 'verbose_name_plural': 'Расписание, Сочи'},
        ),
        migrations.AddField(
            model_name='krdschedule',
            name='time',
            field=models.PositiveIntegerField(choices=[(1, '10:00'), (2, '10:30'), (3, '11:00')], null=True, verbose_name='Тип приема'),
        ),
    ]
