# Generated by Django 3.2.22 on 2023-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0013_alter_krdschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krdschedule',
            name='time',
            field=models.TimeField(choices=[('1', '10:00'), ('2', '10:30'), ('3', '11:00'), ('4', '11:30'), ('5', '12:00'), ('6', '12:30'), ('7', '13:00'), ('8', '13:30'), ('9', '14:00'), ('10', '14:30'), ('11', '15:00'), ('12', '15:30'), ('13', '16:00'), ('14', '16:30'), ('15', '17:00'), ('16', '17:30'), ('17', '18:00'), ('18', '18:30')], null=True, verbose_name='Время'),
        ),
    ]
