# Generated by Django 3.2.22 on 2023-11-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0015_alter_krdschedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krasnodar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skyreg.krdschedule', verbose_name='Расписание Краснодар')),
                ('rostov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skyreg.rndschedule', verbose_name='Расписание Ростов-на-Дону')),
                ('sochi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skyreg.schschedule', verbose_name='Расписание Сочи')),
            ],
            options={
                'verbose_name': 'Общее расписание',
            },
        ),
    ]
