# Generated by Django 3.2.22 on 2023-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0017_auto_20231114_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.PositiveIntegerField(choices=[(1, 'Ростов-на-Дону'), (2, 'Краснодар'), (3, 'Сочи')], null=True, verbose_name='Город')),
                ('num', models.IntegerField(null=True, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
