# Generated by Django 3.2.22 on 2023-11-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0018_cabinets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krdschedule',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='rndschedule',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='schschedule',
            name='cabinet',
        ),
        migrations.DeleteModel(
            name='KRDCabinets',
        ),
        migrations.DeleteModel(
            name='RNDCabinets',
        ),
        migrations.DeleteModel(
            name='SCHCabinets',
        ),
    ]
