# Generated by Django 3.2.22 on 2023-11-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyreg', '0020_auto_20231115_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cabinets',
        ),
    ]
